language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.2
  - 2.5.1
  - 2.6.2
gemfile:
  - Gemfile

matrix:
  fast_finish: true
  exclude:
  - rvm: 2.4.2
    gemfile: Gemfile
  - rvm: 2.5.1
    gemfile: Gemfile
  - rvm: 2.6.2
    gemfile: Gemfile

before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake
