name: CI
on: [push]

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x' ]
        gemfile:
          - activestorage_5_2.gemfile
          - activestorage_6_0.gemfile

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby version
      uses: actions/setup-ruby@master
      with:
        version: ${{ matrix.ruby }}

    - name: Set up bundler
      run: gem install bundler:1.17.3

    - name: Install dependency
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

    - name: bundle install
      run: bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

    - name: test
      run: bundle exec rake
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
